[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-dev", "build-essential"]

[phases.install]
cmds = ["cd backend && pip3 install yt-dlp && npm install"]

[start]
cmd = "cd backend && npm start"