[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-venv", "python3-dev", "build-essential"]

[phases.install]
cmds = [
  "cd backend",
  "python3 -m venv venv",
  "source venv/bin/activate",
  "pip3 install yt-dlp",
  "npm install"
]

[start]
cmd = "cd backend && source venv/bin/activate && npm start"