services:
  - type: web
    name: tikdown-backend
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python -m uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FRONTEND_URL
        value: https://tikdown.netlify.app
        # Replace with your actual frontend URL
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PYDANTIC_VERSION
        value: 1.10.12
      - key: PORT
        value: 10000
    autoDeploy: true